name: Hadolint 👀

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    name: Lint Containerfile using Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
          failure-threshold: warning