name: Hadolint 👀

on:
  push:
    paths:
      - Dockerfile
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    name: Lint Containerfile using Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@master
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
