name: Release and scan 🕷️📦

on:
  push:
    tags:
      - "*.*.*"

permissions:
  actions: write
  contents: write
  security-events: write

env:
  REPOSITORY: docker.io/containerscrew/infratools

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_AUTH_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - name: Set container tag
        id: set_tag
        run: |
          IMAGE_TAG=$(echo "${{ github.ref }}" | sed 's|.*/||')
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Build and push full image
        uses: docker/build-push-action@v6
        with:
          target: full
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REPOSITORY }}:latest,${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Build and push ci image
        uses: docker/build-push-action@v6
        with:
          target: ci
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REPOSITORY }}:latest-ci,${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}-ci

  sec:
    name: sec
    runs-on: ubuntu-latest
    needs: release
    continue-on-error: true
    steps:
      - name: Run Trivy vulnerability scanner (full)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.REPOSITORY }}:${{ needs.release.outputs.image_tag }}"
          format: "sarif"
          output: "trivy-results-full.sarif"
          vuln-type: "os,library"
          ignore-unfixed: false
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_AUTH_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - name: Run Trivy vulnerability scanner (ci)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.REPOSITORY }}:${{ needs.release.outputs.image_tag }}-ci"
          format: "sarif"
          output: "trivy-results-ci.sarif"
          vuln-type: "os,library"
          ignore-unfixed: false
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_AUTH_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - name: Upload Trivy scan results (full)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results-full.sarif"

      - name: Upload Trivy scan results (ci)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results-ci.sarif"
